services:
  postgres:
    container_name: ticket
    image: postgres
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "5051:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./api/app:/app
    ports:
      - "5050:80"