server:
  port: 8080
spring:
  application:
    name: ticket
  datasource:
    password: '123456'
    url: jdbc:postgresql://0.0.0.0:5051/ticket
    username: 'ticket'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: true